name: Chocolatey Package

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Install
        run: |
          choco install -dv -s . easylogusb
      # -
      #   name: Push
      #   run: |
      #     choco push --verbose --api-key=${{ secrets.CHOCOLATE_API_KEY }}
